
name: "test"
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: upload-to-roblox
      uses: ./
      with:
        api-key: ${{ secrets.ROBLOX_API_KEY }}
        experienceId: 3071202796
        file: ./test/binary.rblx